@WebAPI_HostAddress = http://localhost:5285

GET {{WebAPI_HostAddress}}/weatherforecast/
Accept: application/json

### Funciona
### Obtener todas las clases de un usuario 
GET http://localhost:5285/api/schoolclasses?userId=3
Accept: application/json

### Funciona
### Obtener clase por ID
GET http://localhost:5285/api/schoolclasses/6
Accept: application/json


### Crear una clase
POST http://localhost:5285/api/schoolclasses
Content-Type: application/json

{
  "name": "prueba 201 teacher",
  "description": "teacher aaaa",
  "teacher": {
    "id": 2
  }
}

### actualizar una clase
PUT http://localhost:5285/api/schoolclasses/
Content-Type: application/json

{
  "name": "prueba update ",
  "description": "teacher test"
}

### eliminar una clase
DELETE http://localhost:5285/api/schoolclasses/5
Accept: application/json

### Entrar a una clase
POST http://localhost:5285/api/schoolclasses/join
Content-Type: application/json

{
  "joinCode": "9352E5",
  "userId": 3
}

### salir de una clase 
DELETE http://localhost:5285/api/schoolclasses/6/members/7
Content-Type: application/json
