@WebAPI_HostAddress = http://localhost:5285

GET {{WebAPI_HostAddress}}/weatherforecast/
Accept: application/json

### Funciona
### Obtener todas las clases de un usuario 
GET http://localhost:5285/api/SchoolClasses/schoolclass/user/2
Accept: application/json

### Funciona
### Obtener clase por ID
GET http://localhost:5285/api/SchoolClasses/schoolclass/class/2
Accept: application/json


### Crear una clase
POST http://localhost:5285/api/SchoolClasses/schoolclass
Content-Type: application/json

{
  "name": "test 101",
  "description": "Clase introductoria de matemáticas",
  "teacher": {
    "id": 2
  }
}
